services:
  db:
    build: 
      context: ./
      dockerfile: ./Dockerfile.db.main-server
    networks:
      - crickendra_network
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  main-server:
    build: 
      context: ../backend/
      target: final
      dockerfile: ../dockerfiles/Dockerfile.main-server
    restart: always
    networks:
      - crickendra_network
    env_file:
      - ".env"
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: 
      context: ../frontend/
      target: final
      dockerfile: ../dockerfiles/Dockerfile.frontend
    ports:
      - 3000:3000
    restart: always
    networks:
      - crickendra_network
    depends_on:
      main-server:
        condition: service_healthy
  
networks:
  crickendra_network:
    driver: bridge
    
volumes:
  postgres_data:
  